# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 星火时代
description: 专注于大数据和云技术的中文在线媒体， big data, hadoop, spark, data mining, dw, bi, cloud computing, visulization.
author: 星火时代
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.sparkera.net
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

#RSS
feed:
  type: atom
  path: atom.xml
  limit: 20

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
plugins: 
 hexo-generator-feed
 hexo-generator-sitemap

## Themes: http://hexo.io/themes/
theme: hueman

#Comments
disqus_shortname: sparkera
# Deployment
## Docs: http://hexo.io/docs/deployment.html

sitemap:
    path: sitemap.xml

deploy: 
  type: git
  repository: git@github.com:willddy/willddy.github.io.git
  branch: master