# Logo Url
# Please enter an absolute path to your logo file
# or remove the following line with replacing logo-header.png with your own logo
logo:

# Header
menu:
  Home: /
  Categories:  
  About: /about/index.html

# Article list grouped by year
groupByYear: true

# Content
fancybox: true

# Thumbnail
thumbnail: true

# Scroll Loading
scrollLoading: true

# Sidebar
social_links:
  twitter: https://twitter.com/willdu8
  facebook: https://www.facebook.com/will.du.7545
  github: http://github.com/willddy
  rss: /atom.xml
widgets:
- recent_posts
- tagcloud
- archive
- links

# Links
links:
  Hexo: http://hexo.io

# Don't Use Google APIs if you are in google-blocked areas
use_google_apis: UA-40213017-2

# Miscellaneous
google_analytics:
favicon: /image/favicon.ico
fb_admins:
fb_app_id: